Refactor component to use new token structure and expandable mobile
selsa-inube/inubekit-sectionmessage pull request #7
Opened 2024-03-22 21:19 UTC by JanuarAsprilla

the `sectionMessage` component has been refactored to use the new token structure offered by `foundations`

2024-03-27 20:11 UTC, wfercanas requested changes

2024-03-27 20:11 UTC, wfercanas commented on src/SectionMessage/styles.js
> +    inube.sectionMessage[$appearance].background.color};
This property also requires to handle the theme so it can adapt to what the client decides.

2024-03-27 20:11 UTC, wfercanas commented on src/SectionMessage/styles.js
margins || paddings are not aligned with figma:

![image](https://github.com/selsa-inube/inubekit-sectionmessage/assets/36939686/cbde3067-0860-4a25-9870-fbb658c4001f)

2024-03-27 20:11 UTC, wfercanas commented on src/SectionMessage/styles.js
The appearance of this icon should be `dark`
![image](https://github.com/selsa-inube/inubekit-sectionmessage/assets/36939686/4b2cf14f-0e46-4527-8766-73bc5faaa6fd)

2024-03-27 20:11 UTC, wfercanas commented on src/SectionMessage/styles.js
We're not using properly the tokens in all scenarios. Check the light version:
Component:
![image](https://github.com/selsa-inube/inubekit-sectionmessage/assets/36939686/1c198459-b8bf-48f8-8e0c-9af984e9db9e)

Figma:
![image](https://github.com/selsa-inube/inubekit-sectionmessage/assets/36939686/83268ddb-539f-40b1-96e6-6e0285b99977)

Excel:
![image](https://github.com/selsa-inube/inubekit-sectionmessage/assets/36939686/62fce72f-f5c1-42dc-9879-18c8497fcb48)

As you can see, icon, content and countdownBar are dark, not light.

2024-03-27 21:02 UTC, JanuarAsprilla commented on src/SectionMessage/styles.js
> +    inube.sectionMessage[$appearance].background.color};
solved

2024-03-27 21:05 UTC, JanuarAsprilla commented on src/SectionMessage/styles.js
solved

2024-03-27 21:10 UTC, JanuarAsprilla commented on src/SectionMessage/styles.js
solved

2024-04-02 14:53 UTC, wfercanas commented on src/SectionMessage/styles.js
> +    inube.sectionMessage[$appearance].background.color};
This is not solved since you are not using an `||` operator and you're not returning anything from the function:
![image](https://github.com/selsa-inube/inubekit-sectionmessage/assets/36939686/593c4cf1-2376-4018-855e-b9f428b5b9c4)

2024-04-05 22:59 UTC, cmarin001 commented on src/SectionMessage/styles.js
> +    inube.sectionMessage[$appearance].background.color};
solved

2024-04-05 23:26 UTC, merged